export const seedBookList = [
  { title: "Atomic Habits", author: "James Clear", reason: "A practical guide to building better habits and breaking bad ones." },
  { title: "Deep Work", author: "Cal Newport", reason: "Teaches focus and productivity in a distracted world." },
  { title: "The Power of Habit", author: "Charles Duhigg", reason: "Explores the science of habit formation for personal and professional growth." },
  { title: "Mindset", author: "Carol S. Dweck", reason: "Demonstrates the power of a growth mindset for achievement." },
  { title: "The 7 Habits of Highly Effective People", author: "Stephen R. Covey", reason: "Timeless principles for personal and professional effectiveness." },
  { title: "Thinking, Fast and Slow", author: "Daniel Kahneman", reason: "Insights into how we think, make decisions, and avoid cognitive biases." },
  { title: "The Subtle Art of Not Giving a F*ck", author: "Mark Manson", reason: "Encourages focusing on what truly matters for a better life." },
  { title: "Grit", author: "Angela Duckworth", reason: "Shows how perseverance and passion lead to success." },
  { title: "Drive", author: "Daniel H. Pink", reason: "Explains the surprising truth about what motivates us." },
  { title: "The Four Agreements", author: "Don Miguel Ruiz", reason: "Offers practical wisdom for personal freedom and happiness." },
  { title: "The Miracle Morning", author: "Hal Elrod", reason: "Morning routines to transform your life and productivity." },
  { title: "Make Your Bed", author: "William H. McRaven", reason: "Simple habits for resilience and positive change." },
  { title: "Essentialism", author: "Greg McKeown", reason: "Learn to focus on what matters most and eliminate the rest." },
  { title: "The One Thing", author: "Gary Keller", reason: "Focus on the single most important task for extraordinary results." },
  { title: "Can't Hurt Me", author: "David Goggins", reason: "Lessons in mental toughness and pushing past limits." },
  { title: "Start with Why", author: "Simon Sinek", reason: "Discover your purpose to inspire yourself and others." },
  { title: "The Alchemist", author: "Paulo Coelho", reason: "A story about following your dreams and personal legend." },
  { title: "Man's Search for Meaning", author: "Viktor E. Frankl", reason: "Finding meaning and purpose even in the toughest times." },
  { title: "Daring Greatly", author: "Brené Brown", reason: "The power of vulnerability for connection and courage." },
  { title: "The Gifts of Imperfection", author: "Brené Brown", reason: "Letting go of who you think you should be to embrace who you are." },
  { title: "The Power of Now", author: "Eckhart Tolle", reason: "Living in the present moment for peace and clarity." },
  { title: "Awaken the Giant Within", author: "Tony Robbins", reason: "Strategies for taking control of your emotions and life." },
  { title: "Unlimited Power", author: "Tony Robbins", reason: "Unleash your potential with proven personal development techniques." },
  { title: "Tools of Titans", author: "Tim Ferriss", reason: "Tactics and routines from world-class performers." },
  { title: "The 5 AM Club", author: "Robin Sharma", reason: "Early rising habits for productivity and success." },
  { title: "Who Moved My Cheese?", author: "Spencer Johnson", reason: "Adapting to change for success and happiness." },
  { title: "The Magic of Thinking Big", author: "David J. Schwartz", reason: "Inspires you to set high goals and achieve them." },
  { title: "How to Win Friends and Influence People", author: "Dale Carnegie", reason: "Timeless advice for building relationships and influence." },
  { title: "The Success Principles", author: "Jack Canfield", reason: "Principles for achieving your goals and dreams." },
  { title: "The War of Art", author: "Steven Pressfield", reason: "Overcoming resistance to unlock your creative potential." },
  { title: "The Art of Happiness", author: "Dalai Lama", reason: "Insights into cultivating happiness and compassion." },
  { title: "The Happiness Advantage", author: "Shawn Achor", reason: "How happiness fuels success and performance." },
  { title: "Quiet", author: "Susan Cain", reason: "Celebrates the power of introverts in a noisy world." },
  { title: "The Compound Effect", author: "Darren Hardy", reason: "Small choices add up to big results over time." },
  { title: "Principles", author: "Ray Dalio", reason: "Life and work principles for making better decisions." },
  { title: "The Obstacle Is the Way", author: "Ryan Holiday", reason: "Turning adversity into advantage using stoic philosophy." },
  { title: "Ego Is the Enemy", author: "Ryan Holiday", reason: "How to keep your ego in check to achieve greatness." },
  { title: "Daily Stoic", author: "Ryan Holiday", reason: "Daily wisdom for resilience and self-mastery." },
  { title: "The Untethered Soul", author: "Michael A. Singer", reason: "Letting go of limitations for inner peace and freedom." },
  { title: "The Slight Edge", author: "Jeff Olson", reason: "Simple disciplines to create success and happiness." },
  { title: "So Good They Can't Ignore You", author: "Cal Newport", reason: "Building career capital for a fulfilling work life." },
  { title: "Flow", author: "Mihaly Csikszentmihalyi", reason: "Unlocking happiness and productivity through optimal experience." },
  { title: "The 80/20 Principle", author: "Richard Koch", reason: "Focus on the vital few for maximum results." },
  { title: "The Life-Changing Magic of Tidying Up", author: "Marie Kondo", reason: "Declutter your space for clarity and joy." },
  { title: "Getting Things Done", author: "David Allen", reason: "A system for stress-free productivity and organization." },
  { title: "The Willpower Instinct", author: "Kelly McGonigal", reason: "Understanding and strengthening your willpower." },
  { title: "Mindfulness in Plain English", author: "Bhante Henepola Gunaratana", reason: "Practical guide to mindfulness and meditation." },
  { title: "The Road Less Traveled", author: "M. Scott Peck", reason: "Wisdom for personal growth and self-understanding." },
  { title: "The Monk Who Sold His Ferrari", author: "Robin Sharma", reason: "A fable about achieving your dreams and finding fulfillment." },
  { title: "12 Rules for Life", author: "Jordan B. Peterson", reason: "Life lessons for order, meaning, and responsibility." },
  { title: "The Art of Thinking Clearly", author: "Rolf Dobelli", reason: "Avoiding cognitive errors for better decision-making." },
  { title: "The Confidence Gap", author: "Russ Harris", reason: "Overcoming self-doubt to live with confidence." },
  { title: "Thinking in Bets", author: "Annie Duke", reason: "Making smarter decisions when you don't have all the facts." },
  { title: "Ultralearning", author: "Scott H. Young", reason: "Accelerate your learning with intensive, self-directed strategies." },
  { title: "The Charisma Myth", author: "Olivia Fox Cabane", reason: "Learn to be more charismatic and influential." },
  { title: "Stumbling on Happiness", author: "Daniel Gilbert", reason: "Why we often mispredict what will make us happy." },
  { title: "Mind Gym", author: "Gary Mack", reason: "Mental training techniques for peak performance." },
  { title: "The Now Habit", author: "Neil Fiore", reason: "Overcoming procrastination for productivity and peace." },
  { title: "Radical Acceptance", author: "Tara Brach", reason: "Embracing yourself and your life fully." },
  { title: "The Art of Possibility", author: "Rosamund Stone Zander & Benjamin Zander", reason: "Transforming personal and professional life through possibility thinking." },
  { title: "The Five Love Languages", author: "Gary Chapman", reason: "Understanding and expressing love effectively." },
  { title: "Influence", author: "Robert B. Cialdini", reason: "The psychology of persuasion and influence." },
  { title: "Crucial Conversations", author: "Kerry Patterson", reason: "Tools for effective communication in high-stakes situations." },
  { title: "Emotional Intelligence", author: "Daniel Goleman", reason: "How emotional intelligence shapes success." },
  { title: "Originals", author: "Adam Grant", reason: "How non-conformists move the world and drive innovation." },
  { title: "Give and Take", author: "Adam Grant", reason: "The power of generosity and reciprocity for success." },
  { title: "The Art of War", author: "Sun Tzu", reason: "Timeless strategies for competition and leadership." },
  { title: "The 48 Laws of Power", author: "Robert Greene", reason: "Understanding power dynamics and strategy." },
  { title: "Mastery", author: "Robert Greene", reason: "The path to mastering any skill or craft." },
  { title: "The Laws of Human Nature", author: "Robert Greene", reason: "Understanding human behavior for influence and success." },
  { title: "What I Talk About When I Talk About Running", author: "Haruki Murakami", reason: "Reflections on running, writing, and life." },
  { title: "The Art of Learning", author: "Josh Waitzkin", reason: "Master the art of learning and personal growth." },
  { title: "The Art of Noticing", author: "Rob Walker", reason: "Sharpen your attention to enrich your life." },
  { title: "The Power of Full Engagement", author: "Jim Loehr", reason: "Manage energy, not time, for high performance." },
  { title: "The Big Leap", author: "Gay Hendricks", reason: "Overcome hidden barriers to reach your true potential." },
  { title: "Rework", author: "Jason Fried", reason: "Unconventional advice for entrepreneurs and business success." },
  { title: "Show Your Work", author: "Austin Kleon", reason: "Share your creative process to grow your influence." },
  { title: "Steal Like an Artist", author: "Austin Kleon", reason: "Unlock creativity by embracing influence and remixing ideas." },
  { title: "The Dip", author: "Seth Godin", reason: "Knowing when to quit and when to stick for success." },
  { title: "Linchpin", author: "Seth Godin", reason: "Become indispensable by doing remarkable work." },
  { title: "Purple Cow", author: "Seth Godin", reason: "How to stand out in a crowded marketplace." },
  { title: "The Practice", author: "Seth Godin", reason: "Creative habits for shipping your best work." },
  { title: "The Art of Saying No", author: "Damon Zahariades", reason: "Set boundaries and reclaim your time." },
  { title: "Indistractable", author: "Nir Eyal", reason: "Master your attention and beat distractions." },
  { title: "Hooked", author: "Nir Eyal", reason: "How to build habit-forming products." },
  { title: "The Paradox of Choice", author: "Barry Schwartz", reason: "Why too many options can lead to less satisfaction." },
  { title: "The Happiness Project", author: "Gretchen Rubin", reason: "Practical steps for increasing happiness in everyday life." },
  { title: "Why We Sleep", author: "Matthew Walker", reason: "The science of sleep and its impact on health and performance." },
  { title: "Peak", author: "Anders Ericsson", reason: "The secrets of deliberate practice for mastering skills." },
  { title: "The Power of Moments", author: "Chip Heath", reason: "How defining moments shape our lives." },
  { title: "Switch", author: "Chip Heath", reason: "How to change things when change is hard." },
  { title: "Made to Stick", author: "Chip Heath", reason: "Why some ideas survive and others die." },
  { title: "The Motivation Myth", author: "Jeff Haden", reason: "Motivation is the result of action, not the cause." },
  { title: "The Productivity Project", author: "Chris Bailey", reason: "Experiments and insights for becoming more productive." },
  { title: "Eat That Frog!", author: "Brian Tracy", reason: "21 ways to stop procrastinating and get more done." },
  { title: "No Excuses!", author: "Brian Tracy", reason: "The power of self-discipline for success." },
  { title: "The Power of Positive Thinking", author: "Norman Vincent Peale", reason: "Harness positive thinking to improve your life." },
  { title: "The 10X Rule", author: "Grant Cardone", reason: "Achieve massive success by taking massive action." },
  { title: "Unfu*k Yourself", author: "Gary John Bishop", reason: "Get out of your own way and take control of your life." },
  { title: "The Courage to Be Disliked", author: "Ichiro Kishimi", reason: "Break free from others' expectations for happiness." },
  { title: "The Art of Loving", author: "Erich Fromm", reason: "Understanding the true nature of love." },
  { title: "The Road to Character", author: "David Brooks", reason: "Building a deeper, more meaningful character." },
  { title: "The Power of Meaning", author: "Emily Esfahani Smith", reason: "Finding fulfillment by seeking meaning, not just happiness." },
  { title: "The Art of Stillness", author: "Pico Iyer", reason: "The value of slowing down and embracing stillness." },
  { title: "The Power of Intention", author: "Wayne W. Dyer", reason: "Harnessing intention to create the life you want." },
  { title: "The Little Book of Hygge", author: "Meik Wiking", reason: "Discover the Danish secrets to happiness and comfort." },
  { title: "The Book of Joy", author: "Dalai Lama", reason: "Lessons on finding joy in the face of adversity." },
  { title: "The 4-Hour Workweek", author: "Tim Ferriss", reason: "Escape the 9-5 and design your ideal lifestyle." },
  { title: "The 4-Hour Body", author: "Tim Ferriss", reason: "Experiments for rapid fat-loss, muscle gain, and better health." },
  { title: "The 4-Hour Chef", author: "Tim Ferriss", reason: "Learn anything by mastering the meta-skill of learning." },
  { title: "Think and Grow Rich", author: "Napoleon Hill", reason: "Timeless principles for wealth and achievement." },
  { title: "As a Man Thinketh", author: "James Allen", reason: "Your thoughts shape your reality and destiny." },
  { title: "The Richest Man in Babylon", author: "George S. Clason", reason: "Simple lessons in wealth-building and financial wisdom." },
  { title: "The Greatest Salesman in the World", author: "Og Mandino", reason: "Classic wisdom for success in sales and life." },
  { title: "Unlimited Memory", author: "Kevin Horsley", reason: "Techniques to improve memory and learning." },
  { title: "The Confidence Code", author: "Katty Kay", reason: "Unlocking the science and art of self-confidence." },
  { title: "Feel the Fear and Do It Anyway", author: "Susan Jeffers", reason: "Overcoming fear to take positive action." },
  { title: "Psycho-Cybernetics", author: "Maxwell Maltz", reason: "Change your self-image to change your life." },
  { title: "You Are a Badass", author: "Jen Sincero", reason: "Motivational guide to self-belief and success." },
  { title: "You Are a Badass at Making Money", author: "Jen Sincero", reason: "Master your mindset for wealth and abundance." },
  { title: "The Science of Getting Rich", author: "Wallace D. Wattles", reason: "A classic on the mindset and actions for building wealth." },
  { title: "The Seven Spiritual Laws of Success", author: "Deepak Chopra", reason: "Spiritual principles for achieving success and fulfillment." },
  { title: "The Surrender Experiment", author: "Michael A. Singer", reason: "Letting go and trusting life's flow." },
  { title: "The Seat of the Soul", author: "Gary Zukav", reason: "Align your personality with your soul for authentic power." },
  { title: "Ikigai", author: "Hector Garcia & Francesc Miralles", reason: "Discover the Japanese secret to a long and happy life." },
  { title: "The Mountain Is You", author: "Brianna Wiest", reason: "Transform self-sabotage into self-mastery." },
  { title: "Outliers", author: "Malcolm Gladwell", reason: "The story of success and what makes high-achievers different." },
  { title: "Blink", author: "Malcolm Gladwell", reason: "The power of thinking without thinking." },
  { title: "The Tipping Point", author: "Malcolm Gladwell", reason: "How small actions can create big change." },
  { title: "David and Goliath", author: "Malcolm Gladwell", reason: "Advantages of disadvantages and the power of resilience." },
  { title: "High Performance Habits", author: "Brendon Burchard", reason: "Habits of the world's most successful people." },
  { title: "Make Time", author: "Jake Knapp", reason: "Strategies to focus on what matters every day." },
  { title: "The Checklist Manifesto", author: "Atul Gawande", reason: "How checklists improve performance and save lives." },
  { title: "Smarter Faster Better", author: "Charles Duhigg", reason: "The secrets of productivity from top performers." },
  { title: "The Organized Mind", author: "Daniel J. Levitin", reason: "How to manage information overload and stay organized." },
  { title: "The 12 Week Year", author: "Brian P. Moran", reason: "Achieve more in 12 weeks than others do in 12 months." },
  { title: "Wherever You Go, There You Are", author: "Jon Kabat-Zinn", reason: "Mindfulness meditation for everyday life." },
  { title: "Full Catastrophe Living", author: "Jon Kabat-Zinn", reason: "Mindfulness-based stress reduction for health and healing." },
  { title: "The Mindful Way Through Depression", author: "Mark Williams", reason: "Mindfulness techniques for overcoming depression." },
  { title: "The Happiness Trap", author: "Russ Harris", reason: "How to stop struggling and start living using ACT." },
  { title: "Hardwiring Happiness", author: "Rick Hanson", reason: "Train your brain to be stronger, calmer, and happier." },
  { title: "Buddha's Brain", author: "Rick Hanson", reason: "Neuroscience and practical tools for happiness and wisdom." },
  { title: "Self-Compassion", author: "Kristin Neff", reason: "The proven power of being kind to yourself." },
  { title: "Meditations", author: "Marcus Aurelius", reason: "Stoic wisdom for resilience and self-reflection." },
  { title: "Letters from a Stoic", author: "Seneca", reason: "Timeless letters on stoic philosophy and living well." },
  { title: "On the Shortness of Life", author: "Seneca", reason: "Reflections on making the most of your time." },
  { title: "Discourses and Selected Writings", author: "Epictetus", reason: "Teachings on stoic philosophy and personal freedom." },
  { title: "How to Think Like a Roman Emperor", author: "Donald Robertson", reason: "Blending modern psychology and stoic wisdom for life." },
  { title: "A Guide to the Good Life", author: "William B. Irvine", reason: "The ancient art of stoic joy and tranquility." },
  { title: "How to Be a Stoic", author: "Massimo Pigliucci", reason: "Applying stoic philosophy to modern life." },
  { title: "Nudge", author: "Richard H. Thaler", reason: "Improving decisions about health, wealth, and happiness." },
  { title: "Misbehaving", author: "Richard H. Thaler", reason: "The making of behavioral economics and its impact." },
  { title: "Predictably Irrational", author: "Dan Ariely", reason: "The hidden forces that shape our decisions." },
  { title: "The Upside of Irrationality", author: "Dan Ariely", reason: "Unexpected benefits of irrational behaviors." },
  { title: "Dare to Lead", author: "Brené Brown", reason: "Brave leadership through vulnerability and courage." },
  { title: "Rising Strong", author: "Brené Brown", reason: "How getting up after falling leads to growth." },
  { title: "Braving the Wilderness", author: "Brené Brown", reason: "True belonging and the courage to stand alone." },
  { title: "The Body Keeps the Score", author: "Bessel van der Kolk", reason: "Understanding trauma and healing the mind and body." },
  { title: "Option B", author: "Sheryl Sandberg", reason: "Building resilience in the face of adversity." },
  { title: "Emotional Agility", author: "Susan David", reason: "Adapt and thrive by managing your emotions." },
  { title: "Learned Optimism", author: "Martin E. P. Seligman", reason: "How to change your mind and your life with optimism." },
  { title: "Flourish", author: "Martin E. P. Seligman", reason: "A vision for well-being and positive psychology." },
  { title: "Relentless", author: "Tim S. Grover", reason: "What it takes to be unstoppable and achieve greatness." },
  { title: "Winning", author: "Tim S. Grover", reason: "Relentless lessons from champions on winning." },
  { title: "Living with a SEAL", author: "Jesse Itzler", reason: "Pushing your limits by embracing discomfort." },
  { title: "The Energy Bus", author: "Jon Gordon", reason: "10 rules for fueling your life, work, and team with positivity." },
  { title: "Leaders Eat Last", author: "Simon Sinek", reason: "How great leaders build trust and inspire teams." },
  { title: "The 21 Irrefutable Laws of Leadership", author: "John C. Maxwell", reason: "Essential laws for effective leadership." },
  { title: "Developing the Leader Within You 2.0", author: "John C. Maxwell", reason: "Unlock your leadership potential from the inside out." },
  { title: "Good to Great", author: "Jim Collins", reason: "Why some companies and people make the leap to greatness." },
  { title: "Great by Choice", author: "Jim Collins", reason: "Thriving in uncertainty and chaos." },
  { title: "Built to Last", author: "Jim Collins", reason: "Successful habits of visionary companies." },
  { title: "Turning the Flywheel", author: "Jim Collins", reason: "How to build unstoppable momentum for success." },
  { title: "First, Break All the Rules", author: "Marcus Buckingham", reason: "What the world's greatest managers do differently." },
  { title: "Now, Discover Your Strengths", author: "Marcus Buckingham", reason: "Identify and leverage your unique strengths." },
  { title: "StrengthsFinder 2.0", author: "Tom Rath", reason: "A guide to discovering and developing your strengths." },
  { title: "Strengths Based Leadership", author: "Tom Rath", reason: "Build leadership on your unique strengths." },
  { title: "Multipliers", author: "Liz Wiseman", reason: "How the best leaders make everyone smarter." },
  { title: "Impact Players", author: "Liz Wiseman", reason: "How to take the lead, play bigger, and multiply your impact." },
  { title: "Radical Candor", author: "Kim Scott", reason: "How to be a kick-ass boss without losing your humanity." },
  { title: "Thanks for the Feedback", author: "Douglas Stone", reason: "The science and art of receiving feedback well." },
  { title: "Crucial Accountability", author: "Kerry Patterson", reason: "Tools for resolving violated expectations and broken commitments." },
  { title: "Difficult Conversations", author: "Douglas Stone", reason: "How to discuss what matters most." },
  { title: "Creative Confidence", author: "Tom Kelley", reason: "Unleashing the creative potential within us all." },
  { title: "The Artist's Way", author: "Julia Cameron", reason: "A spiritual path to higher creativity." },
  { title: "Big Magic", author: "Elizabeth Gilbert", reason: "Creative living beyond fear." },
  { title: "Bird by Bird", author: "Anne Lamott", reason: "Advice on writing and life, one step at a time." },
  { title: "Designing Your Life", author: "Bill Burnett", reason: "Build a well-lived, joyful life by design." },
  { title: "Pivot", author: "Jenny Blake", reason: "Making smart career changes when you feel stuck." },
  { title: "The Start-Up of You", author: "Reid Hoffman", reason: "Adapt to the future and thrive in your career." },
  { title: "Lean In", author: "Sheryl Sandberg", reason: "Women, work, and the will to lead." },
  { title: "Rich Dad Poor Dad", author: "Robert T. Kiyosaki", reason: "Financial education for wealth and independence." },
  { title: "The Millionaire Next Door", author: "Thomas J. Stanley", reason: "Surprising secrets of America's wealthy." },
  { title: "I Will Teach You to Be Rich", author: "Ramit Sethi", reason: "A no-nonsense approach to personal finance." },
  { title: "The Total Money Makeover", author: "Dave Ramsey", reason: "A proven plan for financial fitness." },
  { title: "Your Money or Your Life", author: "Vicki Robin", reason: "Transform your relationship with money and achieve financial independence." },
  { title: "The Automatic Millionaire", author: "David Bach", reason: "Simple, automatic steps to build wealth." },
  { title: "Unshakeable", author: "Tony Robbins", reason: "Financial freedom through smart investing." },
  { title: "Money Master the Game", author: "Tony Robbins", reason: "7 steps to financial freedom." },
  { title: "The Simple Path to Wealth", author: "JL Collins", reason: "A straightforward guide to financial independence." },
  { title: "Tiny Habits", author: "BJ Fogg", reason: "Small changes for big results in behavior change." },
  { title: "Willpower Doesn't Work", author: "Benjamin Hardy", reason: "Change your environment to change your life." },
  { title: "Better Than Before", author: "Gretchen Rubin", reason: "Master the habits of our everyday lives." },
  { title: "Outer Order, Inner Calm", author: "Gretchen Rubin", reason: "Declutter to create a calmer, happier mind." },
  { title: "Limitless", author: "Jim Kwik", reason: "Upgrade your brain and unlock your exceptional life." },
  { title: "Breaking the Habit of Being Yourself", author: "Joe Dispenza", reason: "How to lose your mind and create a new one." },
  { title: "Becoming Supernatural", author: "Joe Dispenza", reason: "How common people are doing the uncommon." },
  { title: "You Can Heal Your Life", author: "Louise Hay", reason: "The power of thoughts and affirmations for healing." },
  { title: "The Power of Your Subconscious Mind", author: "Joseph Murphy", reason: "Unlock the power of your subconscious for success." },
  { title: "Wishes Fulfilled", author: "Wayne W. Dyer", reason: "Mastering the art of manifesting your desires." },
  { title: "Excuses Begone!", author: "Wayne W. Dyer", reason: "Eliminate excuses and live the life you want." },
  { title: "The Magic of Believing", author: "Claude M. Bristol", reason: "Harness belief to achieve your goals." },
  { title: "The Prophet", author: "Kahlil Gibran", reason: "Timeless poetic wisdom on life and love." },
  { title: "Way of the Peaceful Warrior", author: "Dan Millman", reason: "A spiritual journey to self-discovery and fulfillment." },
  { title: "Warrior of the Light", author: "Paulo Coelho", reason: "A manual for embracing your dreams and destiny." },
  { title: "The Coaching Habit", author: "Michael Bungay Stanier", reason: "Say less, ask more, and change the way you lead." },
  { title: "How to Change", author: "Katy Milkman", reason: "Science-backed strategies for making lasting change." },
  { title: "Think Again", author: "Adam Grant", reason: "The power of knowing what you don't know." },
  { title: "Presence", author: "Amy Cuddy", reason: "Bringing your boldest self to your biggest challenges." },
  { title: "The Alter Ego Effect", author: "Todd Herman", reason: "Harness your hidden superpowers for success." },
  { title: "The Chimp Paradox", author: "Steve Peters", reason: "Manage your mind for confidence, success, and happiness." },
  { title: "The Highly Sensitive Person", author: "Elaine N. Aron", reason: "Thrive as a highly sensitive person in today's world." },
  { title: "Personality Isn't Permanent", author: "Benjamin Hardy", reason: "Break free from self-limiting beliefs and reinvent yourself." },
  { title: "Attached", author: "Amir Levine", reason: "The science of adult attachment for better relationships." },
  { title: "Hold Me Tight", author: "Sue Johnson", reason: "Seven conversations for a lifetime of love." },
  { title: "Nonviolent Communication", author: "Marshall B. Rosenberg", reason: "A language of life for compassion and connection." },
  { title: "Getting the Love You Want", author: "Harville Hendrix", reason: "A guide for couples to build stronger relationships." },
  { title: "Boundaries", author: "Henry Cloud", reason: "When to say yes, how to say no to take control of your life." },
  { title: "Boundaries for Leaders", author: "Henry Cloud", reason: "Results, relationships, and being a leader." },
  { title: "Resilient", author: "Rick Hanson", reason: "How to grow an unshakable core of calm, strength, and happiness." },
  { title: "Spark", author: "John J. Ratey", reason: "The revolutionary new science of exercise and the brain." },
  { title: "Eat Move Sleep", author: "Tom Rath", reason: "Small choices for a healthier, happier life." },
  { title: "The Sleep Revolution", author: "Arianna Huffington", reason: "Transform your life by transforming your sleep." },
  { title: "Thrive", author: "Arianna Huffington", reason: "Redefining success and well-being beyond money and power." },
  { title: "Why Zebras Don't Get Ulcers", author: "Robert M. Sapolsky", reason: "The science of stress and how to manage it." },
  { title: "A Mind for Numbers", author: "Barbara Oakley", reason: "How to excel at math and science, even if you think you can't." },
  { title: "Learning How to Learn", author: "Barbara Oakley", reason: "Powerful mental tools to help you master tough subjects." },
  { title: "Make It Stick", author: "Peter C. Brown", reason: "The science of successful learning." },
  { title: "Never Split the Difference", author: "Chris Voss", reason: "Negotiating as if your life depended on it." },
  { title: "Talk Like TED", author: "Carmine Gallo", reason: "The 9 public-speaking secrets of the world's top minds." },
  { title: "TED Talks", author: "Chris Anderson", reason: "The official TED guide to public speaking." },
  { title: "On Writing Well", author: "William Zinsser", reason: "The classic guide to writing nonfiction." },
  { title: "Write It Down, Make It Happen", author: "Henriette Klauser", reason: "How writing your goals can help you achieve them." },
  { title: "Speak Like Churchill, Stand Like Lincoln", author: "James C. Humes", reason: "21 powerful secrets of history's greatest speakers." },
  { title: "Finish", author: "Jon Acuff", reason: "Give yourself the gift of done and overcome perfectionism." },
  { title: "Start", author: "Jon Acuff", reason: "Punch fear in the face and do work that matters." },
  { title: "Do Over", author: "Jon Acuff", reason: "Rescue your career and discover new opportunities." },
  { title: "Soundtracks", author: "Jon Acuff", reason: "Overcome overthinking to take action in life." },
  { title: "How Will You Measure Your Life?", author: "Clayton M. Christensen", reason: "Finding fulfillment and meaning in work and life." },
  { title: "Men Are from Mars, Women Are from Venus", author: "John Gray", reason: "Improving communication and understanding in relationships." },
  { title: "The Five Dysfunctions of a Team", author: "Patrick Lencioni", reason: "A leadership fable about building cohesive teams." },
  { title: "The Ideal Team Player", author: "Patrick Lencioni", reason: "How to recognize and cultivate essential team virtues." },
  { title: "The Advantage", author: "Patrick Lencioni", reason: "Why organizational health trumps everything else in business." },
  { title: "The Culture Code", author: "Daniel Coyle", reason: "The secrets of highly successful groups." },
  { title: "The Talent Code", author: "Daniel Coyle", reason: "Unlocking talent through deep practice and coaching." },
  { title: "The Little Book of Talent", author: "Daniel Coyle", reason: "52 tips for improving your skills." },
  { title: "The Pomodoro Technique", author: "Staffan Noteberg", reason: "Time management using the Pomodoro method." },
  { title: "Women Who Run with the Wolves", author: "Clarissa Pinkola Estés", reason: "Myths and stories of the wild woman archetype." },
  { title: "Radical Compassion", author: "Tara Brach", reason: "Learning to love yourself and others with compassion." },
  { title: "The Self-Love Experiment", author: "Shannon Kaiser", reason: "A journey to self-acceptance and happiness." },
  { title: "The Six Pillars of Self-Esteem", author: "Nathaniel Branden", reason: "The foundation of healthy self-esteem and its impact." },
  { title: "Love Yourself Like Your Life Depends on It", author: "Kamal Ravikant", reason: "Simple practices for radical self-love." },
  { title: "Goals!", author: "Brian Tracy", reason: "How to set and achieve any goal you desire." },
  { title: "Your Best Year Ever", author: "Michael Hyatt", reason: "A 5-step plan for achieving your most important goals." },
  { title: "Free to Focus", author: "Michael Hyatt", reason: "A total productivity system to achieve more by doing less." },
  { title: "Living Forward", author: "Michael Hyatt", reason: "A proven plan for creating a life with purpose." },
  { title: "The E-Myth Revisited", author: "Michael E. Gerber", reason: "Why most small businesses don't work and what to do about it." },
  { title: "Company of One", author: "Paul Jarvis", reason: "Why staying small is the next big thing for business." },
  { title: "The Lean Startup", author: "Eric Ries", reason: "How today's entrepreneurs use continuous innovation to succeed." },
  { title: "Antifragile", author: "Nassim Nicholas Taleb", reason: "How to thrive in chaos and uncertainty." },
  { title: "Fooled by Randomness", author: "Nassim Nicholas Taleb", reason: "The hidden role of chance in life and markets." },
  { title: "The Black Swan", author: "Nassim Nicholas Taleb", reason: "The impact of rare and unpredictable events." },
  { title: "Extreme Ownership", author: "Jocko Willink", reason: "How U.S. Navy SEALs lead and win." },
  { title: "Discipline Equals Freedom", author: "Jocko Willink", reason: "Field manual for discipline and personal freedom." },
  { title: "The Dichotomy of Leadership", author: "Jocko Willink & Leif Babin", reason: "Balancing leadership principles for effective teams." },
  { title: "Stealing Fire", author: "Steven Kotler", reason: "Unlocking altered states for peak performance." },
  { title: "Abundance", author: "Peter H. Diamandis", reason: "The future is better than you think." },
  { title: "Peak Performance", author: "Brad Stulberg", reason: "Elevate your game, avoid burnout, and thrive." },
  { title: "The Practice of Groundedness", author: "Brad Stulberg", reason: "A transformative path to success that feeds, not crushes, your soul." },
  { title: "Mind Over Mood", author: "Dennis Greenberger", reason: "Change how you feel by changing the way you think." },
  { title: "Feeling Good", author: "David D. Burns", reason: "The new mood therapy for overcoming depression." },
  { title: "The Feeling Good Handbook", author: "David D. Burns", reason: "Tools for overcoming anxiety, depression, and more." },
  { title: "When Panic Attacks", author: "David D. Burns", reason: "The new, drug-free anxiety therapy." },
  { title: "Unwinding Anxiety", author: "Judson Brewer", reason: "New science shows how to break the cycles of worry and fear." },
  { title: "Emotional Intelligence 2.0", author: "Travis Bradberry", reason: "Improve your EQ for personal and professional success." },
  { title: "Social Intelligence", author: "Daniel Goleman", reason: "The new science of human relationships." },
  { title: "Focus", author: "Daniel Goleman", reason: "The hidden driver of excellence." },
  { title: "The Wisdom of the Enneagram", author: "Don Richard Riso", reason: "Personality types for growth and self-understanding." },
  { title: "The Four Tendencies", author: "Gretchen Rubin", reason: "The indispensable personality profiles that reveal how to make your life better." },
  { title: "10% Happier", author: "Dan Harris", reason: "A skeptic's guide to meditation and mindfulness." },
  { title: "Meditation for Fidgety Skeptics", author: "Dan Harris", reason: "A guide to meditation for the rest of us." },
  { title: "Stolen Focus", author: "Johann Hari", reason: "Why you can't pay attention and how to think deeply again." },
  { title: "Lost Connections", author: "Johann Hari", reason: "Uncovering the real causes of depression and unexpected solutions." },
  { title: "The Ruthless Elimination of Hurry", author: "John Mark Comer", reason: "How to stay emotionally healthy and spiritually alive in the chaos of the modern world." },
  { title: "The First 20 Hours", author: "Josh Kaufman", reason: "How to learn anything fast." },
  { title: "The Personal MBA", author: "Josh Kaufman", reason: "A world-class business education in a single volume." },
  { title: "The End of Procrastination", author: "Petr Ludwig", reason: "How to stop postponing and live a fulfilled life." },
  { title: "The Procrastination Equation", author: "Piers Steel", reason: "How to stop putting things off and start getting stuff done." },
  { title: "The Practicing Mind", author: "Thomas M. Sterner", reason: "Develop focus and discipline in your life." },
  { title: "The Power of Regret", author: "Daniel H. Pink", reason: "How looking backward moves us forward." },
  { title: "When", author: "Daniel H. Pink", reason: "The scientific secrets of perfect timing." },
  { title: "To Sell Is Human", author: "Daniel H. Pink", reason: "The surprising truth about moving others." },
  { title: "Creative Calling", author: "Chase Jarvis", reason: "Establish a daily creative practice and pursue your calling." },
  { title: "The Accidental Creative", author: "Todd Henry", reason: "How to be brilliant at a moment's notice." },
  { title: "Die Empty", author: "Todd Henry", reason: "Unleash your best work every day." },
  { title: "Herding Tigers", author: "Todd Henry", reason: "Leading creative people requires a new approach." },
  { title: "Procrastinate on Purpose", author: "Rory Vaden", reason: "5 permissions to multiply your time." },
  { title: "Take the Stairs", author: "Rory Vaden", reason: "7 steps to achieving true success." },
  { title: "Limitless Mind", author: "Jo Boaler", reason: "Learn, lead, and live without barriers." },
  { title: "The Art of Resilience", author: "Ross Edgley", reason: "Strategies for mental toughness and endurance." },
  { title: "13 Things Mentally Strong People Don't Do", author: "Amy Morin", reason: "Take back your power, embrace change, and train your brain for happiness and success." },
  { title: "Stop Doing That Sh*t", author: "Gary John Bishop", reason: "End self-sabotage and demand your life back." },
  { title: "The Resilience Factor", author: "Karen Reivich", reason: "7 keys to finding your inner strength and overcoming life's hurdles." },
  { title: "What Got You Here Won't Get You There", author: "Marshall Goldsmith", reason: "How successful people become even more successful." },
  { title: "Triggers", author: "Marshall Goldsmith", reason: "Creating behavior that lasts and becoming the person you want to be." },
  { title: "Mojo", author: "Marshall Goldsmith", reason: "How to get it, how to keep it, and how to get it back if you lose it." },
  { title: "How Women Rise", author: "Sally Helgesen & Marshall Goldsmith", reason: "Break the 12 habits holding women back from their next raise, promotion, or job." },
  { title: "Conversational Intelligence", author: "Judith E. Glaser", reason: "How great leaders build trust and get extraordinary results." },
  { title: "Everybody Matters", author: "Bob Chapman", reason: "The extraordinary power of caring for your people like family." },
  { title: "From Strength to Strength", author: "Arthur C. Brooks", reason: "Finding success, happiness, and deep purpose in the second half of life." }
];
