import { Book } from "@/types/book";
import {
  calculateWordCount,
  SUMMARY_TYPE_DESCRIPTIONS,
  SummaryGenerationOptions,
  SummaryGenerationResult,
  SummaryType,
} from "@/types/summary";

/**
 * Mock summary service for development/testing
 */
export async function generateMockSummary(
  book: Book,
  summaryType: SummaryType,
): Promise<SummaryGenerationResult> {
 

  // Simulate generation time
  const delay = Math.random() * 2000 + 1000; // 1-3 seconds
  await new Promise((resolve) => setTimeout(resolve, delay));

  const mockContent = generateMockContent(book, summaryType);

  return {
    content: mockContent,
    generationTime: Math.round(delay),
    aiModel: "mock-gpt-4",
    promptVersion: "v1.0-mock",
    usage: {
      promptTokens: 150,
      completionTokens: calculateWordCount(mockContent) * 1.3, // Rough token estimate
      totalTokens: 150 + calculateWordCount(mockContent) * 1.3,
      estimatedCost: 0.01,
    },
    metadata: {
      bookDataSource: book.source,
      hadBookDescription: Boolean(book.description),
      notes: "Generated by mock service for development",
    },
  };
}



function generateMockContent(book: Book, summaryType: SummaryType): string {
  const typeInfo = SUMMARY_TYPE_DESCRIPTIONS[summaryType];

  return `# ${typeInfo.title}: ${book.title}

*${typeInfo.description} - ${typeInfo.readTime}*

## Overview

This is a mock summary of "${book.title}" by ${book.authors.join(", ")}. In a real implementation, this would contain an AI-generated ${summaryType} summary based on the book's content.

${book.description ? `Based on the book description: "${book.description.substring(0, 200)}..."` : "No description available for this book."}

## Key Points

- This is a placeholder summary generated for development purposes
- The actual implementation uses OpenAI to generate real summaries
- Each summary type (${summaryType}) has its own specific format and focus
- Content would be tailored to the specific book and user needs

## Mock Content Structure

The real service would analyze the book's content and generate structured, insightful summaries that help readers understand and appreciate the work.

---

*This mock summary demonstrates the expected format and structure. Enable OpenAI integration for real summary generation.*`;
}
